### ISSUE TITLE
Tornado v5.0.0+ incompatibility 

### ISSUE THREAD

**Issue by dsevero** [python-streamz/streamz#187]
Trying to run with dask backend in Jupyter, looks like there's some clashing with dependencies. 

```python3
from dask.distributed import Client
from streamz import Stream

client = Client()

source = Stream()
source.scatter().map(lambda x: x+1).buffer(8).gather().sink(print)

for i in range(10):
    source.emit(i)
```

As long as I have any version of Tornado that's 5.0.0 or over, I get the following error.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-999e2a726cb5> in <module>()
      9 
     10 for i in range(10):
---> 11     source.emit(i)

~/miniconda3/envs/research/lib/python3.6/site-packages/streamz/core.py in emit(self, x, asynchronous)
    257 
    258                 raise gen.Return(result)
--> 259             return sync(self.loop, _)
    260 
    261     def update(self, x, who=None):

~/miniconda3/envs/research/lib/python3.6/site-packages/streamz/core.py in sync(loop, func, *args, **kwargs)
   1175             return gen.with_timeout(timedelta(seconds=timeout), coro)
   1176 
-> 1177     if not loop._running:
   1178         try:
   1179             return loop.run_sync(make_coro)

AttributeError: 'ZMQIOLoop' object has no attribute '_running'
```

I downgraded to v4.5.3 and now it works fine, but the diagnostics web server won't respond.

**Comment by martindurant** [comment]
Tornado has started to conform to the standard aioloop and zmq now uses tornado/aio directly. Perhaps [`is_running()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.is_running) is the right thing here? See https://github.com/tornadoweb/tornado/pull/2085

**Comment by daniel-severo** [comment]
Looks like the diagnostics is working, but at a different port (not sure why).

**Comment by kivo360** [comment]
Was anybody able to figure this out?

**Comment by CJ-Wright** [comment]
I think the new `sync` works? We might need a release.

**Comment by kivo360** [comment]
Would it work if I ran from git?

**Comment by CJ-Wright** [comment]
Maybe?

**Comment by kivo360** [comment]
I ran it. It does. I tossed the recent release on a different repo. Used to help my library work with everyone.

**Comment by martindurant** [comment]
works ok on master and tornado 5.1.1
