### ISSUE TITLE
visualize() doesn't work with networkx >= 2.4

### ISSUE THREAD

**Issue by jaredmcqueen** [python-streamz/streamz#282]
visualizing a stream works with `networkx < 2.4`.  The error received is:

`AttributeError: 'DiGraph' object has no attribute 'node'`

This stack overflow answer may address the fix, but I haven't tested it yet:
https://stackoverflow.com/questions/49016596/networkx-digraph-attribute-error-self-succ/49016885#49016885

**Comment by martindurant** [comment]
I believe this is fixed in master

**Comment by jdye64** [comment]
@jaredmcqueen Were you able to validate that this is working for you in master now? It is working for me but want to make sure we help you out.

**Comment by jaredmcqueen** [comment]
@jdye64 just tested - works.

In the documentation, there are two mentions of `visualize` needing `graphviz`.  It also needs `networkx` too.  Do you want the documentation updated to mention the need for `networkx` as well?

**Comment by martindurant** [comment]
Sounds reasonable

**Comment by jdye64** [comment]
@jaredmcqueen More documentation is always great! Are you planning on making those changes or would you prefer if someone else did it?

**Comment by jaredmcqueen** [comment]
Pull request added:  https://github.com/python-streamz/streamz/pull/292
