### ISSUE TITLE
Accumulate example not running?

### ISSUE THREAD

**Issue by gamesbook** [python-streamz/streamz#421]
Working with version 0.6.2 in Python 3.7

I seem to get an error running accumulate as per the example (https://streamz.readthedocs.io/en/latest/api.html#streamz.accumulate):
```
>>> from streamz import Stream
>>> source = Stream()
>>> source.accumulate(lambda acc, x: acc + x).sink(print)
<sink: print>
>>> 
>>> for i in range(5): source.emit()
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: emit() missing 1 required positional argument: 'x'
```

**Comment by martindurant** [comment]
> `source.emit()`

You forgot to include any data. Should be something like `source.emit(5)`. The example emits the value of `i`.

**Comment by gamesbook** [comment]
Apologies; posting at the end of a long day!
